version: '3.9'
services:
 ms-sql-server:
  image: mcr.microsoft.com/mssql/server:2022-latest
  environment:
   ACCEPT_EULA: "Y"
   SA_PASSWORD: "Tivani1301"
  ports:
   - "1433:1433"
 suitsupply-web:
  build: .
  ports:
   - "8080:80"
  depends_on:
   - "ms-sql-server"